# Generated by Django 4.1.7 on 2023-04-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='senha',
        ),
    ]
