# Generated by Django 4.1.7 on 2023-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_address_person_endereço_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('endereço', models.TextField()),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
